/**
 * Generate the BotC sidebar CSS from a settings object.
 *
 * Settings:
 *   bg1  {string}  Gradient start colour  (default #f4e8d0)
 *   bg2  {string}  Gradient mid colour    (default #e8dcc8)
 *   bg3  {string}  Gradient end colour    (default #f4e8d0)
 *   bc   {string}  Border / divider colour (default #8b6f47)
 *   tc   {string}  Name text colour        (default #000000)
 *   ff   {string}  Font-family             (default '')
 *   fs   {number}  Name font-size (px)     (default 14)
 *   m    {boolean} Show jagged-edge mask   (default true)
 *   w    {number}  Sidebar width (px)      (default 270)
 *   preview {boolean} Replace fixed with relative for iframe preview
 */
function generateCSS(settings) {
  const {
    bg1 = '#f4e8d0',
    bg2 = '#e8dcc8',
    bg3 = '#f4e8d0',
    bc  = '#8b6f47',
    tc  = '#000000',
    ff  = '',
    fs  = 14,
    m   = true,
    w   = 270,
    preview = false,
  } = settings;

  const fontFamilyRule = ff ? `font-family: ${ff} !important;` : '';
  const positionRule   = preview ? 'position: relative !important;' : 'position: fixed !important;';
  const heightRules    = preview
    ? ''
    : `  min-height: 100vh !important;\n  max-height: 100vh !important;`;

  const clipPath = m
    ? `clip-path: polygon(0% 0%, 1% 0.5%, 2% 1%, 2.5% 1.2%, 3% 1.5%, 3.5% 2%, 4% 2.5%, 3.5% 3%, 4% 3.5%, 4.5% 4%, 5% 4.5%, 5.5% 5%, 6% 5.5%, 5.5% 6%, 6% 6.5%, 6.5% 7%, 7% 7.5%, 7.5% 8%, 7% 8.5%, 7.5% 9%, 6.5% 9.5%, 7% 10%, 7.5% 10.5%, 8% 11%, 7.5% 12%, 7% 12.5%, 7.5% 13%, 8% 14%, 8.5% 15%, 9% 16%, 8.5% 17%, 8% 18%, 8.5% 19%, 9% 20%, 9.5% 21%, 10% 23%, 9.5% 25%, 9% 27%, 9.5% 29%, 10% 30%, 10.5% 31%, 11% 32%, 10.5% 35%, 10% 37%, 10.5% 39%, 11% 40%, 11.5% 41%, 12% 42%, 11.5% 45%, 11% 47%, 11.5% 49%, 10.5% 50%, 10% 52%, 9.5% 54%, 9% 57%, 9.5% 59%, 8.5% 60%, 8% 62%, 7.5% 64%, 7% 67%, 7.5% 69%, 6.5% 70%, 6% 72%, 5.5% 74%, 5% 77%, 5.5% 79%, 4.5% 80%, 4% 82%, 3.5% 84%, 3% 87%, 3.5% 89%, 2.5% 90%, 2% 92%, 1.5% 94%, 1% 96%, 0.5% 98%, 0% 100%, 100% 100%, 100% 0%) !important;`
    : '';

  return `/* ============================================================
 * BotC-CSS — Stations Docked Right (Large Token Display)
 * Generated by https://github.com/Stayingfalse/BotC-CSS
 * ============================================================ */

aside.character.tab:not(.character-open):not(.positioned) {
  ${positionRule}
  top: 0 !important;
  right: 0 !important;
  bottom: 0 !important;
  width: ${w}px !important;
${heightRules}
  display: flex !important;
  flex-direction: column !important;
  padding: 40px 0 0 30px !important;
  margin: 0 !important;
  overflow: visible !important;
  box-sizing: border-box !important;

  footer, .jinxes { display: none !important; }

  &::before {
    content: '' !important;
    position: absolute !important;
    top: 0 !important;
    left: 0 !important;
    right: 0 !important;
    bottom: 0 !important;
    background: linear-gradient(135deg, ${bg1} 0%, ${bg2} 50%, ${bg3} 100%) !important;
    border-left: 3px solid ${bc} !important;
    box-shadow: -4px 0 10px rgba(0, 0, 0, 0.3) !important;
    z-index: -1 !important;
    ${clipPath}
  }

  .container {
    all: unset !important;
    display: flex !important;
    flex-direction: column !important;
    justify-content: flex-start !important;
    width: 100% !important;
    height: 100% !important;
    box-sizing: border-box !important;
    padding: 10px 5px !important;
    overflow-y: auto !important;
    overflow-x: hidden !important;
  }

  section {
    all: unset !important;
    display: flex !important;
    flex-direction: column !important;
    justify-content: flex-start !important;
    width: 100% !important;
    height: 100% !important;
    overflow: visible !important;
  }

  .team {
    all: unset !important;
    display: contents !important;

    &:not(.demon):not(.jinxes):after,
    &.jinxes:before {
      content: "" !important;
      display: block !important;
      width: 90% !important;
      height: 2px !important;
      min-height: 2px !important;
      margin: 8px auto !important;
      background: linear-gradient(to right, transparent, ${bc} 20%, ${bc} 80%, transparent) !important;
      box-shadow: 0 1px 2px rgba(0, 0, 0, 0.3) !important;
    }

    aside { display: none !important; }

    ul {
      all: unset !important;
      display: contents !important;
    }

    li {
      all: unset !important;
      display: flex !important;
      align-items: center !important;
      width: 100% !important;
      box-sizing: border-box !important;
      position: relative !important;
      overflow: visible !important;
      flex: 1 !important;
      min-height: 3.5vh !important;
      padding: 10px !important;
      transition: all 0.3s ease !important;
    }
  }

  .icon {
    display: inline-block !important;
    position: absolute !important;
    width: 200px !important;
    height: 95% !important;
    right: 0 !important;
    bottom: 50% !important;
    background-position: 110% center !important;
    background-size: 100% !important;
    background-repeat: no-repeat !important;
    opacity: 0.5 !important;
    pointer-events: none !important;
    z-index: 0 !important;
    overflow: visible !important;
    transition: opacity 0.3s ease !important;
  }

  .almanac { display: none !important; }

  .jinx .icon { display: none !important; }

  .role {
    all: unset !important;
    display: block !important;
    width: 100% !important;
    position: static !important;
    padding-left: 5px !important;
    overflow: visible !important;
    z-index: 1 !important;
  }

  .name {
    all: unset !important;
    display: block !important;
    width: 100% !important;
    text-align: left !important;
    font-size: ${fs}px !important;
    color: ${tc} !important;
    font-weight: bold !important;
    text-transform: uppercase !important;
    text-shadow: 1px 1px 2px rgba(255, 255, 255, 0.8) !important;
    ${fontFamilyRule}
    transition: color 0.3s ease, text-shadow 0.3s ease !important;
  }

  .label, [role="tab"] { display: none !important; }

  .ability {
    all: unset !important;
    display: none !important;
  }

  li:hover:not(.bootlegger li) {
    background: rgba(0, 0, 0, 0.85) !important;
    border: 2px solid rgba(255, 255, 255, 0.3) !important;
    border-radius: 8px !important;
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.5) !important;
    z-index: 10000 !important;
    flex: none !important;
    min-height: auto !important;
    padding-right: 15px !important;
    max-width: 100% !important;

    .ability {
      all: unset !important;
      display: block !important;
      position: static !important;
      margin-top: 6px !important;
      color: white !important;
      font-size: 13px !important;
      line-height: 1.4 !important;
      text-align: left !important;
      word-wrap: break-word !important;
      overflow-wrap: break-word !important;
      white-space: normal !important;
      max-width: 100% !important;
      box-sizing: border-box !important;
      animation: fadeIn 0.3s ease !important;
    }

    .name {
      color: white !important;
      text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.8) !important;
    }

    .icon {
      opacity: 0.2 !important;
      top: 60% !important;
      bottom: auto !important;
      transform: translateY(-50%) !important;
      height: 80% !important;
    }
  }

  .bootlegger {
    ul {
      all: unset !important;
      display: flex !important;
      flex-direction: column !important;
      position: relative !important;
      width: 100% !important;
      box-sizing: border-box !important;
      padding: 10px !important;
      min-height: 35px !important;
      flex: 1 !important;
      transition: all 0.3s ease !important;
    }

    li:first-child {
      all: unset !important;
      display: block !important;
      width: 100% !important;
      position: relative !important;
      font-size: 0 !important;
      color: transparent !important;
      min-height: 35px !important;
    }

    li:not(:first-child) { display: none !important; }

    &:hover {
      ul {
        background: rgba(0, 0, 0, 0.5) !important;
        border: 2px solid rgba(255, 255, 255, 0.3) !important;
        border-radius: 8px !important;
        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.5) !important;
        z-index: 10000 !important;
        flex: none !important;
        min-height: auto !important;
        padding-right: 15px !important;
        max-width: 100% !important;
      }

      li {
        display: list-item !important;
        position: static !important;
        list-style-type: disc !important;
        list-style-position: inside !important;
        width: 100% !important;
        padding: 4px 0 !important;
        color: white !important;
        font-size: 13px !important;
        line-height: 1.4 !important;
        margin-left: 15px !important;
        word-wrap: break-word !important;
        overflow-wrap: break-word !important;
        white-space: normal !important;
        max-width: calc(100% - 15px) !important;
        box-sizing: border-box !important;
        animation: fadeIn 0.3s ease !important;
        min-height: auto !important;

        .icon {
          opacity: 0.05 !important;
          top: 50% !important;
          bottom: auto !important;
          transform: translateY(-50%) !important;
          height: 80% !important;
          z-index: -1 !important;
        }
      }
    }
  }
}

@keyframes fadeIn {
  from {
    opacity: 0;
    transform: translateY(-5px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}
`;
}

module.exports = { generateCSS };
