/**
 * Generate CSS for the Token Motion tool.
 *
 * This targets the circular player tokens in the BotC online grimoire,
 * NOT the character list tokens in the sidebar script view.
 *
 * Settings:
 *   mt  {string}  Motion type: spin | rock | hybrid | random
 *   mw  {string}  When to apply: off | always | hover | not-hover
 *   ms  {number}  Speed multiplier (0.2 – 3)
 *   me  {string}  CSS easing function
 */

const DEFAULTS = {
  mt: 'spin',
  mw: 'hover',
  ms: 1,
  me: 'ease-in-out',
};

function pickNumber(value, fallback, min, max) {
  const parsed = Number(value);
  if (!Number.isFinite(parsed)) return fallback;
  return Math.min(max, Math.max(min, parsed));
}

function pickOption(value, fallback, allowed) {
  const normalised = String(value ?? '').trim();
  return allowed.includes(normalised) ? normalised : fallback;
}

/**
 * Build the animation declarations for player tokens.
 * Targets #app .player .token — the circular character images in the grimoire.
 */
function buildMotionCss({ motionType, motionWhen, motionEase, spinDuration, rockDuration, hybridDuration }) {
  if (motionWhen === 'off') return '';

  const applyWhen = (animationValue, playerFilter = '') => {
    if (motionWhen === 'hover') {
      return `#app .player${playerFilter}:hover .token {
  animation: ${animationValue};
}`;
    }

    if (motionWhen === 'not-hover') {
      return `#app .player${playerFilter}:not(:hover) .token {
  animation: ${animationValue};
}`;
    }

    // 'always'
    return `#app .player${playerFilter} .token {
  animation: ${animationValue};
}`;
  };

  if (motionType === 'random') {
    return `${applyWhen(`${spinDuration}s botcTokenSpin ${motionEase} infinite`, ':nth-child(odd)')}

${applyWhen(`${rockDuration}s botcTokenRock ${motionEase} infinite`, ':nth-child(even)')}`;
  }

  if (motionType === 'spin') {
    return applyWhen(`${spinDuration}s botcTokenSpin ${motionEase} infinite`);
  }

  if (motionType === 'rock') {
    return applyWhen(`${rockDuration}s botcTokenRock ${motionEase} infinite`);
  }

  return applyWhen(`${hybridDuration}s botcTokenHybrid ${motionEase} infinite`);
}

function generateTokenMotionCSS(settings) {
  const {
    mt = DEFAULTS.mt,
    mw = DEFAULTS.mw,
    ms = DEFAULTS.ms,
    me = DEFAULTS.me,
  } = settings;

  const motionType  = pickOption(mt, DEFAULTS.mt, ['spin', 'rock', 'hybrid', 'random']);
  const motionWhen  = pickOption(mw, DEFAULTS.mw, ['off', 'always', 'hover', 'not-hover']);
  const motionEase  = pickOption(me, DEFAULTS.me, ['linear', 'ease', 'ease-in', 'ease-out', 'ease-in-out']);
  const motionSpeed = pickNumber(ms, DEFAULTS.ms, 0.2, 3);

  const spinDuration   = (30 / motionSpeed).toFixed(2);
  const rockDuration   = (2  / motionSpeed).toFixed(2);
  const hybridDuration = (18 / motionSpeed).toFixed(2);

  const motionCss = buildMotionCss({ motionType, motionWhen, motionEase, spinDuration, rockDuration, hybridDuration });

  return `/* ============================================================
 * BotC-CSS — Player Token Motion (Grimoire)
 * Applies animation to player tokens on the BotC online grimoire board.
 * Generated by https://github.com/Stayingfalse/BotC-CSS
 * ============================================================ */

@keyframes botcTokenSpin {
  0%   { rotate: 0deg; }
  50%  { rotate: 1046deg; }
  100% { rotate: 0deg; }
}

@keyframes botcTokenRock {
  0%   { rotate: 0deg; }
  25%  { rotate: 45deg; }
  75%  { rotate: -45deg; }
  100% { rotate: 0deg; }
}

@keyframes botcTokenHybrid {
  0%   { rotate: 0deg; }
  20%  { rotate: 210deg; }
  40%  { rotate: 480deg; }
  65%  { rotate: 340deg; }
  85%  { rotate: 560deg; }
  100% { rotate: 360deg; }
}

${motionCss}
`;
}

module.exports = { generateTokenMotionCSS };
